Finished home page for youtube
DanCarl857/youtube-clone pull request #1
Opened 2019-06-04 09:17 UTC by DanCarl857

2019-06-04 23:54 UTC, efrapp requested changes
# The page looks nice!

The page is pretty close to the original but please address the followings suggestions:

1. Check this issue: #2 
2. Add a live version of the project, for that you can use [Github pages](https://pages.github.com/)
3. Add descriptive information to the project, what is the purpose? what concepts did you apply? and the author.
4. Check [HTML validator](https://validator.w3.org/) to the `index` page

You made a great job organizing the files in folders and the indentation is well used.

Please address the suggestions and send a code review again.

2019-06-04 23:54 UTC, efrapp commented on styles/main.css
> +   grid-template-areas: "video video aside"
Try always to get the lines aligned.

2019-06-04 23:54 UTC, efrapp commented on styles/main.css
> +.header__logo {
Why do you use `__` syntax to name the classes? does it have an special meaning?

2019-06-04 23:54 UTC, efrapp commented on styles/main.css
> +  height: 100%;
Be consistent with the indentation, some times you use 1 space and other you use more than one.

2019-06-04 23:54 UTC, efrapp commented on styles/main.css
> +       grid-template-areas:       "video"
Also, check the indentation here.

2019-06-05 07:55 UTC, DanCarl857 commented
thanks for the review @efrapp

2019-06-05 22:10 UTC, efrapp approved these changes
# You are done! 👍 

All the changes were made, so you can continue. I want to insist on the benefits of having a descriptive Readme. Bear in mind other people can see your work and good documentation is always needed.

No need to send a code review again.

I wish you the best in your path!

2019-06-06 08:23 UTC, merged